# from .mtgpis import MultiTaskGaussianProcessImplicitSurfaces
from .gpis import GaussianProcessImplicitSurfaces
# from .mtgpis2 import MultiTaskGaussianProcessImplicitSurfaces2
from .mtgpis_pytorch import MultiTaskGaussianProcessImplicitSurfaces